.PHONY: clean All

All:
	@echo "----------Building project:[ sndwrk - Release ]----------"
	@"$(MAKE)" -f  "sndwrk.mk" && "$(MAKE)" -f  "sndwrk.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ sndwrk - Release ]----------"
	@"$(MAKE)" -f  "sndwrk.mk" clean
